services:
  app:
    build:
      context: .
      target: dev
    command: pnpm run start:dev
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./nest-cli.json:/app/nest-cli.json
      - /app/node_modules
    environment:
      NODE_ENV: development
