name: leovegas-test

services:
  test-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: leovegas_test
    ports:
      - '3307:3306'
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-ptest' ]
      interval: 3s
      timeout: 3s
      retries: 20
